os:
    - linux
    - osx

language: rust
rust:
    - stable
    - beta
    - nightly

env:
    - RUST_BACKTRACE=1

matrix:
    allow_failures:
        - rust: beta
        - rust: nightly
    fast_finish: true

install:
    - rustup component add clippy

script:
    - bin/test.sh

cache:
    cargo: true
    directories:
        - crates/target/

before_deploy:
    - ./gen_doc.sh
    - cp -r target/doc/* gh-pages/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: gh-pages/
  on:
      branch: master
      condition: "$TRAVIS_RUST_VERSION = stable && $TRAVIS_OS_NAME = linux"
